# Generated by Django 3.0 on 2022-05-05 13:02

from django.db import migrations


def migrate_profile_data(apps, schema_editor):
    try:
        OldProfile = apps.get_model("oc_lettings_site", "Profile")
        NewProfile = apps.get_model("profiles", "Profile")
    except LookupError:
        return

    NewProfile.objects.bulk_create(
        NewProfile(
            user=old_profile.user,
            favorite_city=old_profile.favorite_city
        )
        for old_profile in OldProfile.objects.all()
    )


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('oc_lettings_site', '0004_auto_20220505_1254')
    ]

    operations = [
        migrations.RunPython(migrate_profile_data)
    ]
