version: 2.1
workflows:
  build_master:
    jobs:
      - build_and_test
      - package:
          filters:
            branches:
              only: master
          requires:
            - build_and_test
      - publish_artefact:
          requires:
            - package
          filters:
            branches:
              only: master
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: bdibon/oc-lettings
    docker:
      - image: circleci/buildpack-deps:stretch
jobs:
  build_and_test:
    docker:
      - image: cimg/python:3.8.10
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run Tests
          command: pytest
      - persist_to_workspace:
          root: ~/app
          paths:
            - .
  package:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: .
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: docker build -t $IMAGE_NAME:latest .
      - run:
          name: Archive Docker Image
          command: docker save -o image.tar $IMAGE_NAME
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
  publish_artefact:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load archived Docker Image
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            IMAGE_TAG="0.0.${CIRCLE_BUILD_NUM}"
            docker tag $IMAGE_NAME:latest $IMAGE_NAME:$IMAGE_TAG
            docker push $IMAGE_NAME:latest
            docker push $IMAGE_NAME:$IMAGE_TAG
