version: 2.1

workflows:
  build_test_deploy:
    jobs:
      - build_and_test

jobs:
  build_and_test:
    docker:
      - image: cimg/python:3.8.10
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run Tests
          command: pytest
      - persist_to_workspace:
          root: ~/app
          paths:
            - .
