# Generated by Django 3.0 on 2022-05-05 10:24

from django.db import migrations


def migrate_lettings_data(apps, schema_editor):
    try:
        OldAddress = apps.get_model("oc_lettings_site", "Address")
        OldLetting = apps.get_model("oc_lettings_site", "Letting")
        NewAddress = apps.get_model("lettings", "Address")
        NewLetting = apps.get_model("lettings", "Letting")
    except LookupError:
        return
    
    NewAddress.objects.bulk_create(
        NewAddress(
            number=old_address.number,
            street=old_address.street,
            city=old_address.city,
            state=old_address.state,
            zip_code=old_address.zip_code,
            country_iso_code=old_address.country_iso_code,
        )
        for old_address in OldAddress.objects.all()
    )

    NewLetting.objects.bulk_create(
        NewLetting(
            title=old_letting.title,
            address=NewAddress.objects.get(pk=old_letting.address.id)
        )
        for old_letting in OldLetting.objects.all()
    )

class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0002_auto_20220504_1340'),
        ('lettings', '0001_initial')
    ]

    operations = [
        migrations.RunPython(migrate_lettings_data)
    ]
